export const EMPLOYER_CREATE_REQUEST = "EMPLOYER_CREATE_REQUEST";
export const EMPLOYER_CREATE_FAILURE = "EMPLOYER_CREATE_FAILURE";
export const EMPLOYER_CREATE_SUCCESS = "EMPLOYER_CREATE_SUCCESS";

export const EMPLOYER_PROFILE_REQUEST = "EMPLOYER_PROFILE_REQUEST";
export const EMPLOYER_PROFILE_FAILURE = "EMPLOYER_PROFILE_FAILURE";
export const EMPLOYER_PROFILE_SUCCESS = "EMPLOYER_PROFILE_SUCCESS";
