export const WORKER_CREATE_REQUEST = "WORKER_CREATE_REQUEST";
export const WORKER_CREATE_FAILURE = "WORKER_CREATE_FAILURE";
export const WORKER_CREATE_SUCCESS = "WORKER_CREATE_SUCCESS";

export const WORKER_PROFILE_REQUEST = "WORKER_PROFILE_REQUEST";
export const WORKER_PROFILE_FAILURE = "WORKER_PROFILE_FAILURE";
export const WORKER_PROFILE_SUCCESS = "WORKER_PROFILE_SUCCESS";
